/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#819986",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary": "#251207",
        "on-primary-fixed-variant": "#364c3c",
        "inverse-on-surface": "#f4f0e7",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e6e2d8",
        "surface-bright": "#fdf9ef",
        "on-tertiary-fixed-variant": "#5a4134",
        "outline": "#737973",
        "outline-variant": "#c3c8c1",
        "secondary-container": "#fed488",
        "inverse-surface": "#31312a",
        "surface": "#fdf9ef",
        "tertiary-fixed": "#ffdbca",
        "secondary-fixed": "#ffdea5",
        "secondary-fixed-dim": "#e9c176",
        "background": "#fdf9ef",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#b4cdb8",
        "surface-container-low": "#f7f3e9",
        "on-surface": "#1c1c16",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dddad0",
        "secondary": "#775a19",
        "on-secondary-container": "#785a1a",
        "surface-container-high": "#ece8de",
        "tertiary-container": "#3c261a",
        "on-primary-fixed": "#0b2013",
        "on-primary": "#ffffff",
        "on-surface-variant": "#434843",
        "on-secondary-fixed": "#261900",
        "primary": "#061b0e",
        "surface-tint": "#4d6453",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b4cdb8",
        "surface-container": "#f1eee4",
        "surface-variant": "#e6e2d8",
        "primary-fixed": "#d0e9d4",
        "primary-container": "#1b3022",
        "on-tertiary-container": "#ac8c7b",
        "on-background": "#1c1c16",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#e3bfad",
        "on-tertiary-fixed": "#2a170c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1280px",
        "base": "8px",
        "gutter": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        serif: ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "label-caps": ["Manrope"],
        "body-lg": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg-mobile": ["Playfair Display"],
        "headline-lg": ["Playfair Display"]
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
